sudo: required
services:
  - docker

before_install:
  - docker build -t dockergopi123456/docker-react -f Dockerfile.dev .

script:
  - docker run dockergopi123456/docker-react npm run test -- --coverage
